In [161]:
import pandas as pd
import numpy as np

In [162]:
df = pd.read_csv("API/Carbon Emission.csv")

In [163]:
df.shape

(10000, 20)

In [164]:
df.head(1)

,Body Type,Sex,Diet,How Often Shower,Heating Energy Source,Transport,Vehicle Type,Social Activity,Monthly Grocery Bill,Frequency of Traveling by Air,Vehicle Monthly Distance Km,Waste Bag Size,Waste Bag Weekly Count,How Long TV PC Daily Hour,How Many New Clothes Monthly,How Long Internet Daily Hour,Energy efficiency,Recycling,Cooking_With,CarbonEmission
0,overweight,female,pescatarian,daily,coal,public,NaN,often,230,frequently,210,large,4,7,26,1,No,['Metal'],"['Stove', 'Oven']",2238

In [165]:
df.tail(1)

,Body Type,Sex,Diet,How Often Shower,Heating Energy Source,Transport,Vehicle Type,Social Activity,Monthly Grocery Bill,Frequency of Traveling by Air,Vehicle Monthly Distance Km,Waste Bag Size,Waste Bag Weekly Count,How Long TV PC Daily Hour,How Many New Clothes Monthly,How Long Internet Daily Hour,Energy efficiency,Recycling,Cooking_With,CarbonEmission
9999,obese,male,pescatarian,twice a day,wood,private,electric,sometimes,115,never,9952,small,4,11,6,0,Sometimes,"['Plastic', 'Glass', 'Metal']","['Oven', 'Grill', 'Airfryer']",826

In [166]:
df.columns

Index(['Body Type', 'Sex', 'Diet', 'How Often Shower', 'Heating Energy Source',
       'Transport', 'Vehicle Type', 'Social Activity', 'Monthly Grocery Bill',
       'Frequency of Traveling by Air', 'Vehicle Monthly Distance Km',
       'Waste Bag Size', 'Waste Bag Weekly Count', 'How Long TV PC Daily Hour',
       'How Many New Clothes Monthly', 'How Long Internet Daily Hour',
       'Energy efficiency', 'Recycling', 'Cooking_With', 'CarbonEmission'],
      dtype='object')

In [167]:
df["Sex"]

0       female
1       female
2         male
3         male
4       female
         ...
9995      male
9996    female
9997    female
9998      male
9999      male
Name: Sex, Length: 10000, dtype: object

In [168]:
df[df.columns[2]]

0       pescatarian
1        vegetarian
2          omnivore
3          omnivore
4        vegetarian
           ...
9995       omnivore
9996          vegan
9997     vegetarian
9998          vegan
9999    pescatarian
Name: Diet, Length: 10000, dtype: object

In [169]:
df[df["Sex"] == "male"]

,Body Type,Sex,Diet,How Often Shower,Heating Energy Source,Transport,Vehicle Type,Social Activity,Monthly Grocery Bill,Frequency of Traveling by Air,Vehicle Monthly Distance Km,Waste Bag Size,Waste Bag Weekly Count,How Long TV PC Daily Hour,How Many New Clothes Monthly,How Long Internet Daily Hour,Energy efficiency,Recycling,Cooking_With,CarbonEmission
2,overweight,male,omnivore,more frequently,wood,private,petrol,never,138,never,2472,small,1,14,47,6,Sometimes,['Metal'],"['Oven', 'Microwave']",2595
3,overweight,male,omnivore,twice a day,wood,walk/bicycle,NaN,sometimes,157,rarely,74,medium,3,20,5,7,Sometimes,"['Paper', 'Plastic', 'Glass', 'Metal']","['Microwave', 'Grill', 'Airfryer']",1074
5,overweight,male,vegetarian,less frequently,wood,public,NaN,sometimes,144,frequently,658,large,1,22,18,9,Sometimes,"['Paper', 'Glass', 'Metal']","['Stove', 'Oven', 'Microwave']",1647
8,overweight,male,omnivore,daily,wood,public,NaN,never,200,frequently,1376,medium,3,3,31,15,Yes,['Glass'],"['Microwave', 'Grill', 'Airfryer']",2494
11,obese,male,vegetarian,more frequently,coal,walk/bicycle,NaN,never,111,very frequently,69,medium,5,9,4,4,Sometimes,[],"['Stove', 'Oven', 'Microwave']",3226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,obese,male,omnivore,more frequently,coal,public,NaN,never,120,rarely,421,large,3,10,33,6,Yes,"['Paper', 'Plastic']","['Stove', 'Grill', 'Airfryer']",2077
9993,underweight,male,pescatarian,more frequently,wood,walk/bicycle,NaN,sometimes,118,frequently,78,medium,3,8,14,10,Sometimes,[],['Oven'],1794
9995,obese,male,omnivore,twice a day,coal,private,hybrid,sometimes,230,never,268,medium,5,12,27,9,Yes,[],['Microwave'],2408
9998,underweight,male,vegan,more frequently,coal,private,petrol,often,179,rarely,8688,medium,5,19,14,5,Sometimes,"['Paper', 'Metal']","['Stove', 'Microwave', 'Grill', 'Airfryer']",4574
9999,obese,male,pescatarian,twice a day,wood,private,electric,sometimes,115,never,9952,small,4,11,6,0,Sometimes,"['Plastic', 'Glass', 'Metal']","['Oven', 'Grill', 'Airfryer']",826

In [170]:
df[df.index == 2]

,Body Type,Sex,Diet,How Often Shower,Heating Energy Source,Transport,Vehicle Type,Social Activity,Monthly Grocery Bill,Frequency of Traveling by Air,Vehicle Monthly Distance Km,Waste Bag Size,Waste Bag Weekly Count,How Long TV PC Daily Hour,How Many New Clothes Monthly,How Long Internet Daily Hour,Energy efficiency,Recycling,Cooking_With,CarbonEmission
2,overweight,male,omnivore,more frequently,wood,private,petrol,never,138,never,2472,small,1,14,47,6,Sometimes,['Metal'],"['Oven', 'Microwave']",2595

In [171]:
df.loc[4, "Sex"]

'female'

In [172]:
df.shape

(10000, 20)

In [173]:
df.dropna(inplace=True)

In [174]:
df.shape

(3279, 20)

In [175]:
df.head(10)

,Body Type,Sex,Diet,How Often Shower,Heating Energy Source,Transport,Vehicle Type,Social Activity,Monthly Grocery Bill,Frequency of Traveling by Air,Vehicle Monthly Distance Km,Waste Bag Size,Waste Bag Weekly Count,How Long TV PC Daily Hour,How Many New Clothes Monthly,How Long Internet Daily Hour,Energy efficiency,Recycling,Cooking_With,CarbonEmission
2,overweight,male,omnivore,more frequently,wood,private,petrol,never,138,never,2472,small,1,14,47,6,Sometimes,['Metal'],"['Oven', 'Microwave']",2595
4,obese,female,vegetarian,daily,coal,private,diesel,often,266,very frequently,8457,large,1,3,5,6,Yes,['Paper'],['Oven'],4743
6,underweight,female,vegan,less frequently,wood,private,hybrid,never,56,rarely,5363,medium,4,9,11,19,Sometimes,[],"['Grill', 'Airfryer']",1832
13,underweight,female,vegan,less frequently,electricity,private,lpg,sometimes,111,rarely,2893,large,6,13,16,10,Sometimes,"['Plastic', 'Glass', 'Metal']","['Stove', 'Oven', 'Microwave', 'Grill', 'Airfr...",1732
18,underweight,male,vegan,more frequently,electricity,private,petrol,often,126,very frequently,7622,medium,2,6,37,9,Sometimes,[],['Stove'],5272
20,normal,male,vegan,twice a day,electricity,private,electric,often,282,rarely,2237,large,6,0,8,5,No,"['Plastic', 'Glass', 'Metal']","['Oven', 'Grill', 'Airfryer']",1300
23,obese,male,vegetarian,daily,coal,private,diesel,often,165,frequently,472,small,4,17,24,20,Yes,"['Paper', 'Glass']",['Microwave'],2582
24,overweight,male,vegan,daily,coal,private,diesel,sometimes,62,very frequently,5737,medium,1,5,20,20,Yes,"['Paper', 'Metal']","['Grill', 'Airfryer']",4284
33,normal,female,pescatarian,daily,wood,private,lpg,often,280,very frequently,8320,small,5,9,0,4,Sometimes,"['Paper', 'Metal']","['Stove', 'Oven', 'Grill', 'Airfryer']",3911
44,overweight,male,omnivore,daily,wood,private,electric,often,294,very frequently,9488,small,5,16,20,18,Yes,['Glass'],[],3141

In [176]:
df.reset_index(inplace=True)
df.drop(["index"], axis=1, inplace=True)

In [177]:
df

,Body Type,Sex,Diet,How Often Shower,Heating Energy Source,Transport,Vehicle Type,Social Activity,Monthly Grocery Bill,Frequency of Traveling by Air,Vehicle Monthly Distance Km,Waste Bag Size,Waste Bag Weekly Count,How Long TV PC Daily Hour,How Many New Clothes Monthly,How Long Internet Daily Hour,Energy efficiency,Recycling,Cooking_With,CarbonEmission
0,overweight,male,omnivore,more frequently,wood,private,petrol,never,138,never,2472,small,1,14,47,6,Sometimes,['Metal'],"['Oven', 'Microwave']",2595
1,obese,female,vegetarian,daily,coal,private,diesel,often,266,very frequently,8457,large,1,3,5,6,Yes,['Paper'],['Oven'],4743
2,underweight,female,vegan,less frequently,wood,private,hybrid,never,56,rarely,5363,medium,4,9,11,19,Sometimes,[],"['Grill', 'Airfryer']",1832
3,underweight,female,vegan,less frequently,electricity,private,lpg,sometimes,111,rarely,2893,large,6,13,16,10,Sometimes,"['Plastic', 'Glass', 'Metal']","['Stove', 'Oven', 'Microwave', 'Grill', 'Airfr...",1732
4,underweight,male,vegan,more frequently,electricity,private,petrol,often,126,very frequently,7622,medium,2,6,37,9,Sometimes,[],['Stove'],5272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3274,normal,female,vegetarian,more frequently,wood,private,petrol,never,89,rarely,4482,large,5,15,17,22,Sometimes,[],"['Oven', 'Microwave']",2999
3275,obese,male,omnivore,twice a day,coal,private,hybrid,sometimes,230,never,268,medium,5,12,27,9,Yes,[],['Microwave'],2408
3276,normal,female,vegan,twice a day,coal,private,lpg,never,234,frequently,5316,extra large,3,14,8,24,Sometimes,"['Paper', 'Plastic']","['Stove', 'Microwave']",3084
3277,underweight,male,vegan,more frequently,coal,private,petrol,often,179,rarely,8688,medium,5,19,14,5,Sometimes,"['Paper', 'Metal']","['Stove', 'Microwave', 'Grill', 'Airfryer']",4574
3278,obese,male,pescatarian,twice a day,wood,private,electric,sometimes,115,never,9952,small,4,11,6,0,Sometimes,"['Plastic', 'Glass', 'Metal']","['Oven', 'Grill', 'Airfryer']",826

In [178]:
df.loc[0, "Sex"]

'male'

In [179]:
for column in df.columns:
    if not isinstance(df.loc[0, column], (int, float, np.number)):
        df[column], unique = pd.factorize(df[column])

In [180]:
df

,Body Type,Sex,Diet,How Often Shower,Heating Energy Source,Transport,Vehicle Type,Social Activity,Monthly Grocery Bill,Frequency of Traveling by Air,Vehicle Monthly Distance Km,Waste Bag Size,Waste Bag Weekly Count,How Long TV PC Daily Hour,How Many New Clothes Monthly,How Long Internet Daily Hour,Energy efficiency,Recycling,Cooking_With,CarbonEmission
0,0,0,0,0,0,0,0,0,138,0,2472,0,1,14,47,6,0,0,0,2595
1,1,1,1,1,1,0,1,1,266,1,8457,1,1,3,5,6,1,1,1,4743
2,2,1,2,2,0,0,2,0,56,2,5363,2,4,9,11,19,0,2,2,1832
3,2,1,2,2,2,0,3,2,111,2,2893,1,6,13,16,10,0,3,3,1732
4,2,0,2,0,2,0,0,1,126,1,7622,2,2,6,37,9,0,2,4,5272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3274,3,1,1,0,0,0,0,0,89,2,4482,1,5,15,17,22,0,2,0,2999
3275,1,0,0,3,1,0,2,2,230,0,268,2,5,12,27,9,1,2,6,2408
3276,3,1,2,3,1,0,3,0,234,3,5316,3,3,14,8,24,0,11,15,3084
3277,2,0,2,0,1,0,0,1,179,2,8688,2,5,19,14,5,0,5,14,4574
3278,1,0,3,3,0,0,4,2,115,0,9952,0,4,11,6,0,0,3,5,826

In [181]:
left = df[df["How Often Shower"] >= 1]
right = df[df["How Often Shower"] < 1]

In [182]:
left.shape

(2464, 20)